"""create feature and parcel tables

Revision ID: 6d52fa13665b
Revises: a9aa131c32bb
Create Date: 2026-08-31 11:17:37.619168

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d52fa13665b'
down_revision: Union[str, Sequence[str], None] = 'a9aa131c32bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_feature_type'), 'features', ['feature_type'], unique=False)
    op.create_index(op.f('ix_features_processing_job_id'), 'features', ['processing_job_id'], unique=False)
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('processing_job_id', sa.Integer(), nullable=False),
    sa.Column('parcel_code', sa.String(length=50), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('perimeter_m', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validity_status', sa.String(length=30), server_default='VALID', nullable=False),
    sa.Column('review_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_parcel_code'), 'parcels', ['parcel_code'], unique=False)
    op.create_index(op.f('ix_parcels_processing_job_id'), 'parcels', ['processing_job_id'], unique=False)
    op.create_index(op.f('ix_parcels_project_id'), 'parcels', ['project_id'], unique=False)
    op.create_index(op.f('ix_parcels_review_status'), 'parcels', ['review_status'], unique=False)
    op.create_index(op.f('ix_parcels_validity_status'), 'parcels', ['validity_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_validity_status'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_review_status'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_project_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_processing_job_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_parcel_code'), table_name='parcels')
    op.drop_index('idx_parcels_geometry', table_name='parcels', postgresql_using='gist')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_index(op.f('ix_features_processing_job_id'), table_name='features')
    op.drop_index(op.f('ix_features_feature_type'), table_name='features')
    op.drop_index('idx_features_geometry', table_name='features', postgresql_using='gist')
    op.drop_table('features')
    # ### end Alembic commands ###
