"""add project survey boundary

Revision ID: 748da0b45037
Revises: 6d52fa13665b
Create Date: 2026-08-31 13:39:34.125510

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748da0b45037'
down_revision: Union[str, Sequence[str], None] = '6d52fa13665b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('survey_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_survey_boundary', table_name='projects', postgresql_using='gist')
    op.drop_column('projects', 'survey_boundary')
    # ### end Alembic commands ###
