"""add parcel review comment

Revision ID: b7d0d168ef62
Revises: 7a8a2f246600
Create Date: 2026-08-31 17:24:41.855906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d0d168ef62'
down_revision: Union[str, Sequence[str], None] = '7a8a2f246600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('review_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'review_comment')
    # ### end Alembic commands ###
